/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.ConexaoPostgresql;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Estoque
 */
public class ConsultaProdutos extends javax.swing.JInternalFrame {

    private ConexaoPostgresql Conexao;
    
    /**
     * Creates new form ConsultaProdutos
     */
    public ConsultaProdutos() {
        initComponents();
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaProdutos().setVisible(true);
            }
        });
    }

    public void centralizar(JDesktopPane dp) {
        Dimension ds = dp.getSize();
        Dimension dw = this.getSize();
        this.setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jrbNomeProduto = new javax.swing.JRadioButton();
        jrbCodigoFabricante = new javax.swing.JRadioButton();
        jrbCodigoSistema = new javax.swing.JRadioButton();
        jrbFabricanteProduto = new javax.swing.JRadioButton();
        jtfPesquisa = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Consulta de Produtos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Código Fabricante", "Nome", "Fabricante", "Qtde Min.", "Qtde Máx.", "Qtde Estoque", "Qtde Trânsito", "Saldo", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(9).setResizable(false);
            jTable1.getColumnModel().getColumn(9).setPreferredWidth(30);
        }

        jrbNomeProduto.setSelected(true);
        jrbNomeProduto.setText("Nome do Produto");
        jrbNomeProduto.setFocusable(false);

        jrbCodigoFabricante.setText("Código do Fabricante");
        jrbCodigoFabricante.setFocusable(false);

        jrbCodigoSistema.setText("Código do Sistema");
        jrbCodigoSistema.setFocusable(false);

        jrbFabricanteProduto.setText("Fabricante do Produto");
        jrbFabricanteProduto.setFocusable(false);

        jtfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPesquisaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1234, Short.MAX_VALUE)
                    .addComponent(jtfPesquisa)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jrbCodigoFabricante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbCodigoSistema)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbFabricanteProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbNomeProduto)
                        .addGap(373, 373, 373)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbCodigoFabricante)
                    .addComponent(jrbCodigoSistema)
                    .addComponent(jrbNomeProduto)
                    .addComponent(jrbFabricanteProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisaKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            CarregaProduto();
        }
    }//GEN-LAST:event_jtfPesquisaKeyPressed

    private void CarregaProduto(){

        String SQL, Transito, Saldo;

        SQL = "select tpr.codigo, tpr.codigo_fornecedor, tpr.nome, (tp.nome) as fabricante, tpr.qtde_min, tpr.qtde_max, tpr.qtde, ";
        SQL = SQL + "(ts.nome) as status ";
        SQL = SQL + "from t_produto tpr ";        
        SQL = SQL + "inner join t_pessoa tp on tp.codigo = tpr.codigo_cad_fornecedor ";
        SQL = SQL + "inner join t_status ts on ts.codigo = tpr.codigo_ativo ";
        
        if (jrbNomeProduto.isSelected()){
            SQL = SQL + "where UPPER(tpr.nome) like '%" + jtfPesquisa.getText().toUpperCase() + "%' and tpr.exclusao = 0 ";
        } else if (jrbCodigoFabricante.isSelected()) {
            SQL = SQL + "where UPPER(tpr.codigo_fornecedor) like '%" + jtfPesquisa.getText().toUpperCase() + "%' and tpr.exclusao = 0 ";
        } else if (jrbCodigoSistema.isSelected()){
            SQL = SQL + "where tpr.codigo = " + jtfPesquisa.getText() + " and tpr.exclusao = 0 ";
        } else if (jrbFabricanteProduto.isSelected()){
            SQL = SQL + "inner join t_pessoa tp on tp.codigo = tpr.codigo_cad_fornecedor ";
            SQL = SQL + "where UPPER(tp.nome) like '%" + jtfPesquisa.getText().toUpperCase() + "%' and tpr.exclusao = 0 ";
        }

        SQL = SQL + "order by tpr.codigo ";

        Conexao = new ConexaoPostgresql();
        Conexao.Conectar() ;
        Conexao.setSQL(SQL);

        ((DefaultTableModel) jTable1.getModel()).setNumRows(0);
        jTable1.updateUI();

        ResultSet RS = Conexao.Consultar();

        try{

            while (RS.next()){                
                Transito = Transito(RS.getString("codigo"));
                Saldo = String.valueOf(Integer.parseInt(RS.getString("qtde")) - Integer.parseInt(Transito));
                
                DefaultTableModel Tabela = (DefaultTableModel) jTable1.getModel();
                Object[] CarLinha = {RS.getString("codigo"),RS.getString("codigo_fornecedor"),RS.getString("nome"),RS.getString("fabricante"),RS.getString("qtde_min"),RS.getString("qtde_max"),RS.getString("qtde"),Transito,Saldo,RS.getString("status")};
                Tabela.addRow(CarLinha);
            }

        }catch (Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro na validação: " + Erro);
        }

        Conexao.Desconectar();

    }    

    private String Transito (String Produto){
        
        String SQL = "";
        String qtde = "null";
        
        SQL = "select COALESCE(sum(tvi.qtde_liberada),0) as qtde_transito ";
        SQL = SQL + "from t_viagem_item tvi ";
        SQL = SQL + "inner join t_viagem tv on tv.codigo = tvi.codigo_viagem ";
        SQL = SQL + "where produto_cod = " + Produto + " ";
        SQL = SQL + "and tv.data_finalizar is null ";
        SQL = SQL + "and tv.exclusao = 0";
        
        Conexao = new ConexaoPostgresql();
        Conexao.Conectar() ;
        Conexao.setSQL(SQL);
        ResultSet RS = Conexao.Consultar();
        
        try{
            if (RS.next()){  
                qtde = RS.getString("qtde_transito");
            }
        }catch (Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro na validação: " + Erro);
        }       
        
        return qtde;
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton jrbCodigoFabricante;
    private javax.swing.JRadioButton jrbCodigoSistema;
    private javax.swing.JRadioButton jrbFabricanteProduto;
    private javax.swing.JRadioButton jrbNomeProduto;
    private javax.swing.JTextField jtfPesquisa;
    // End of variables declaration//GEN-END:variables
}
