/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.ConexaoPostgresql;
import classes.Funcoes;
import classes.TextDocument;
import java.awt.Dimension;
import java.sql.ResultSet;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author morpheus
 */
public class ConsultaAgenda extends javax.swing.JInternalFrame {
    
    private ConexaoPostgresql Conexao;
    private Funcoes Fun;    
    private TextDocument TD;

    /**
     * Creates new form ConsultaAgenda
     */
    public ConsultaAgenda() {
        initComponents();
        RadioButton();
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAgenda().setVisible(true);
            }
        });
    }

    public void centralizar(JDesktopPane dp) {
        Dimension ds = dp.getSize();
        Dimension dw = this.getSize();
        this.setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }
    
    private void CarregaAgenda(){
        
        String SQL;

        SQL = "select tp.codigo, tp.nome, tp.cpfcnpj, tp.rgie, (tp.endereco || ' - ' || tp.numero || ' - ' || tp.bairro) as endereco, ";
        SQL = SQL + "tp.fone1, tp.fone2, tp.cel1, tp.cel2 ";
        SQL = SQL + "from t_pessoa tp ";        
        SQL = SQL + "where exclusao = 0 ";
        
        if (jrbNome.isSelected()){
            SQL = SQL + "and UPPER(tp.nome) like '%" + jtfNome.getText().toUpperCase() + "%' ";
        } else if (jrbRGIE.isSelected()) {
            SQL = SQL + "and UPPER(tp.rgie) like '%" + jtfRgIe.getText().toUpperCase() + "%' ";
        } else if (jrbCPFCNPJ.isSelected()){
            SQL = SQL + "and UPPER(tp.cpfcnpj) like '%" + jtfCpfCnpj.getText().toUpperCase() + "%' ";
        } else if (jrbTelefone.isSelected()){
            SQL = SQL + "and UPPER(tp.fone1) like '%" + jtfTelefone.getText().toUpperCase() + "%' ";
            SQL = SQL + "or UPPER(tp.fone2) like '%" + jtfTelefone.getText().toUpperCase() + "%' ";
        } else if (jrbCelular.isSelected()){
            SQL = SQL + "and UPPER(tp.cel1) like '%" + jtfCelular.getText().toUpperCase() + "%' ";
            SQL = SQL + "or UPPER(tp.cel2) like '%" + jtfCelular.getText().toUpperCase() + "%' ";
        }

        SQL = SQL + "order by tp.nome ";

        Conexao = new ConexaoPostgresql();
        Conexao.Conectar() ;
        Conexao.setSQL(SQL);

        ((DefaultTableModel) jTable1.getModel()).setNumRows(0);
        jTable1.updateUI();

        ResultSet RS = Conexao.Consultar();

        try{

            while (RS.next()){                
                DefaultTableModel Tabela = (DefaultTableModel) jTable1.getModel();
                Object[] CarLinha = {RS.getString("codigo"),RS.getString("nome"),RS.getString("endereco"),RS.getString("fone1"),RS.getString("cel1"),RS.getString("fone2"),RS.getString("cel2")};
                Tabela.addRow(CarLinha);
            }

        }catch (Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro na validação: " + Erro);
        }

        Conexao.Desconectar();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The jrbRGIEActionPerformedcontent of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jlbNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jtfCpfCnpj = new javax.swing.JFormattedTextField();
        jlbCpfCnpj = new javax.swing.JLabel();
        jtfRgIe = new javax.swing.JFormattedTextField();
        jlbRgIe = new javax.swing.JLabel();
        jtfTelefone = new javax.swing.JFormattedTextField();
        jlbTelefone = new javax.swing.JLabel();
        jtfCelular = new javax.swing.JFormattedTextField();
        jlbCelular = new javax.swing.JLabel();
        jrbNome = new javax.swing.JRadioButton();
        jrbRGIE = new javax.swing.JRadioButton();
        jrbCPFCNPJ = new javax.swing.JRadioButton();
        jrbTelefone = new javax.swing.JRadioButton();
        jrbCelular = new javax.swing.JRadioButton();
        jbtExecPesquisa = new javax.swing.JButton();

        setClosable(true);
        setTitle("Consulta Agenda");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Endereço", "Telefone", "Celular", "Telefone 2", "Celular 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(30);
        }

        jlbNome.setText("Nome");

        jtfNome.setDocument(TD = new TextDocument(50));
        jtfNome.setEnabled(false);

        jtfCpfCnpj.setEnabled(false);

        jlbCpfCnpj.setText("CPF / CNPJ");

        jtfRgIe.setEnabled(false);

        jlbRgIe.setText("RG / IE");

        jtfTelefone.setFormatterFactory(Fun.setFormatoTelefone());
        jtfTelefone.setEnabled(false);

        jlbTelefone.setText("Telefone");

        jtfCelular.setFormatterFactory(Fun.setFormatoTelefone());
        jtfCelular.setEnabled(false);

        jlbCelular.setText("Celular");

        buttonGroup1.add(jrbNome);
        jrbNome.setSelected(true);
        jrbNome.setText("Nome");
        jrbNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNomeActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbRGIE);
        jrbRGIE.setText("RG / IE");
        jrbRGIE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbRGIEActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbCPFCNPJ);
        jrbCPFCNPJ.setText("CPF / CNPJ");
        jrbCPFCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCPFCNPJActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbTelefone);
        jrbTelefone.setText("Telefone");
        jrbTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTelefoneActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbCelular);
        jrbCelular.setText("Celular");
        jrbCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCelularActionPerformed(evt);
            }
        });

        jbtExecPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Pesquisa.png"))); // NOI18N
        jbtExecPesquisa.setText("Pesquise!");
        jbtExecPesquisa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtExecPesquisa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtExecPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExecPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jrbNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbRGIE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbCPFCNPJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbCelular))
                    .addComponent(jlbNome)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbRgIe)
                                    .addComponent(jtfRgIe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbCpfCnpj)
                                    .addComponent(jtfCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbTelefone)
                                    .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbCelular))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtExecPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbNome)
                    .addComponent(jrbRGIE)
                    .addComponent(jrbCPFCNPJ)
                    .addComponent(jrbTelefone)
                    .addComponent(jrbCelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfRgIe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlbRgIe)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlbTelefone)
                                        .addComponent(jlbCelular))
                                    .addGap(5, 5, 5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlbCpfCnpj)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtfCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtExecPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtExecPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExecPesquisaActionPerformed
        
        CarregaAgenda();
        
    }//GEN-LAST:event_jbtExecPesquisaActionPerformed

    private void jrbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNomeActionPerformed
        RadioButton();
    }//GEN-LAST:event_jrbNomeActionPerformed

    private void jrbRGIEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbRGIEActionPerformed
        RadioButton();
    }//GEN-LAST:event_jrbRGIEActionPerformed

    private void jrbCPFCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCPFCNPJActionPerformed
        RadioButton();
    }//GEN-LAST:event_jrbCPFCNPJActionPerformed

    private void jrbTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTelefoneActionPerformed
        RadioButton();
    }//GEN-LAST:event_jrbTelefoneActionPerformed

    private void jrbCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCelularActionPerformed
        RadioButton();
    }//GEN-LAST:event_jrbCelularActionPerformed

    private void RadioButton(){
        
        if (jrbNome.isSelected()){
            jtfNome.setEnabled(true);
            jtfRgIe.setEnabled(false);
            jtfCpfCnpj.setEnabled(false);
            jtfTelefone.setEnabled(false);
            jtfCelular.setEnabled(false);
        } else if (jrbRGIE.isSelected()) {
            jtfNome.setEnabled(false);
            jtfRgIe.setEnabled(true);
            jtfCpfCnpj.setEnabled(false);
            jtfTelefone.setEnabled(false);
            jtfCelular.setEnabled(false);
        } else if (jrbCPFCNPJ.isSelected()){
            jtfNome.setEnabled(false);
            jtfRgIe.setEnabled(false);
            jtfCpfCnpj.setEnabled(true);
            jtfTelefone.setEnabled(false);
            jtfCelular.setEnabled(false);
        } else if (jrbTelefone.isSelected()){
            jtfNome.setEnabled(false);
            jtfRgIe.setEnabled(false);
            jtfCpfCnpj.setEnabled(false);
            jtfTelefone.setEnabled(true);
            jtfCelular.setEnabled(false);
        } else if (jrbCelular.isSelected()){
            jtfNome.setEnabled(false);
            jtfRgIe.setEnabled(false);
            jtfCpfCnpj.setEnabled(false);
            jtfTelefone.setEnabled(false);
            jtfCelular.setEnabled(true);
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtExecPesquisa;
    private javax.swing.JLabel jlbCelular;
    private javax.swing.JLabel jlbCpfCnpj;
    private javax.swing.JLabel jlbNome;
    private javax.swing.JLabel jlbRgIe;
    private javax.swing.JLabel jlbTelefone;
    private javax.swing.JRadioButton jrbCPFCNPJ;
    private javax.swing.JRadioButton jrbCelular;
    private javax.swing.JRadioButton jrbNome;
    private javax.swing.JRadioButton jrbRGIE;
    private javax.swing.JRadioButton jrbTelefone;
    private javax.swing.JFormattedTextField jtfCelular;
    private javax.swing.JFormattedTextField jtfCpfCnpj;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JFormattedTextField jtfRgIe;
    private javax.swing.JFormattedTextField jtfTelefone;
    // End of variables declaration//GEN-END:variables
}
