/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PesquisaProduto.java
 *
 * Created on 26/12/2010, 11:04:17
 */

package telas;

import classes.ConexaoPostgresql;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jeff
 */
public class PesquisaProduto extends javax.swing.JInternalFrame {

    private ConexaoPostgresql Conexao;
    private CadastroProduto Pr;

    /** Creates new form PesquisaProduto */
    public PesquisaProduto() {
        initComponents();        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jtfPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jrbNomeProduto = new javax.swing.JRadioButton();
        jrbCodigoFabricante = new javax.swing.JRadioButton();
        jrbCodigoSistema = new javax.swing.JRadioButton();
        jrbFabricanteProduto = new javax.swing.JRadioButton();

        setClosable(true);
        setTitle("Pesquisa de Produtos");

        jtfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPesquisaKeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Código Fabricante", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(550);
        }

        buttonGroup1.add(jrbNomeProduto);
        jrbNomeProduto.setSelected(true);
        jrbNomeProduto.setText("Nome do Produto");
        jrbNomeProduto.setFocusable(false);
        jrbNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNomeProdutoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbCodigoFabricante);
        jrbCodigoFabricante.setText("Código do Fabricante");
        jrbCodigoFabricante.setFocusable(false);

        buttonGroup1.add(jrbCodigoSistema);
        jrbCodigoSistema.setText("Código do Sistema");
        jrbCodigoSistema.setFocusable(false);

        buttonGroup1.add(jrbFabricanteProduto);
        jrbFabricanteProduto.setText("Fabricante do Produto");
        jrbFabricanteProduto.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addComponent(jtfPesquisa)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrbCodigoFabricante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbCodigoSistema)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbFabricanteProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbNomeProduto)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbCodigoFabricante)
                    .addComponent(jrbCodigoSistema)
                    .addComponent(jrbNomeProduto)
                    .addComponent(jrbFabricanteProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisaKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            CarregaProduto();
        }
}//GEN-LAST:event_jtfPesquisaKeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        Pr.CarregaDados(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());

        this.dispose();
        
}//GEN-LAST:event_jTable1MouseClicked

    private void jrbNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbNomeProdutoActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisaProduto().setVisible(true);
            }
        });
    }

    public void centralizar(JDesktopPane dp) {
        Dimension ds = dp.getSize();
        Dimension dw = this.getSize();
        this.setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }

    public void SetProduto(CadastroProduto Prod){
        this.Pr = Prod;
    }

    private void CarregaProduto(){

        String SQL;

        SQL = "select tpr.codigo, tpr.codigo_fornecedor, tpr.nome from t_produto tpr ";        
        
        if (jrbNomeProduto.isSelected()){
            SQL = SQL + "where UPPER(tpr.nome) like '%" + jtfPesquisa.getText().toUpperCase() + "%' and tpr.exclusao = 0 ";
        } else if (jrbCodigoFabricante.isSelected()) {
            SQL = SQL + "where UPPER(tpr.codigo_fornecedor) like '%" + jtfPesquisa.getText().toUpperCase() + "%' and tpr.exclusao = 0 ";
        } else if (jrbCodigoSistema.isSelected()){
            SQL = SQL + "where tpr.codigo = " + jtfPesquisa.getText() + " and tpr.exclusao = 0 ";
        } else if (jrbFabricanteProduto.isSelected()){
            SQL = SQL + "inner join t_pessoa tp on tp.codigo = tpr.codigo_cad_fornecedor ";
            SQL = SQL + "where UPPER(tp.nome) like '%" + jtfPesquisa.getText().toUpperCase() + "%' and tpr.exclusao = 0 ";
        }
        
        SQL = SQL + "order by tpr.codigo ";

        Conexao = new ConexaoPostgresql();
        Conexao.Conectar() ;
        Conexao.setSQL(SQL);

        ((DefaultTableModel) jTable1.getModel()).setNumRows(0);
        jTable1.updateUI();

        ResultSet RS = Conexao.Consultar();

        try{

            while (RS.next()){
                DefaultTableModel Tabela = (DefaultTableModel) jTable1.getModel();
                Object[] CarLinha = {RS.getString("codigo"),RS.getString("codigo_fornecedor"),RS.getString("nome")};
                Tabela.addRow(CarLinha);
            }

        }catch (Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro na validação: " + Erro);
        }

        Conexao.Desconectar();

    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton jrbCodigoFabricante;
    private javax.swing.JRadioButton jrbCodigoSistema;
    private javax.swing.JRadioButton jrbFabricanteProduto;
    private javax.swing.JRadioButton jrbNomeProduto;
    private javax.swing.JTextField jtfPesquisa;
    // End of variables declaration//GEN-END:variables

}
