/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SubPesquisaCidade.java
 *
 * Created on Dec 14, 2009, 10:01:58 PM
 */

package telas;

import classes.ConexaoPostgresql;
import classes.TextDocument;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jeff
 */
public class SubPesquisaPessoa extends javax.swing.JInternalFrame {

    private ConexaoPostgresql Conexao;
    private MovimentacaoEntrada MovEnt;
    private MovimentacaoSaida MovSai;
    private MovimentacaoViagemAbrir MovViaA;
    private MovimentacaoOrcamento MovOrc;
    private ConsultaEntrada ConEnt;
    private ConsultaSaida ConSai;
    private ConsultaViagem ConVia;
    private ConsultaOrcamento ConOrc;
    private RelatorioEntrada RelEnt;
    private RelatorioSaida RelSai;
    private RelatorioViagem RelVia;
    private TextDocument TD;
    
    String Meleca;

    /** Creates new form SubPesquisaCidade */
    public SubPesquisaPessoa() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setTitle("Procura Fabricante");

        jtfPesquisa.setDocument(TD = new TextDocument(20));
        jtfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPesquisaKeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(400);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfPesquisa)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        System.out.println(Meleca);

        if (Meleca.equals("FornecedorEntrada")) {
            MovEnt.NomeFornecedorViaF12(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()));
        } else if (Meleca.equals("FornecedorSaida")) {
            MovSai.NomeFornecedorViaF12(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()));
        } else if (Meleca.equals("ViagemAbrir")) {
            MovViaA.NomePessoaViaF12(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()));
        } else if (Meleca.equals("ConsultaEntrada")) {
            ConEnt.NomeFornecedorViaF12(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()));
        } else if (Meleca.equals("ConsultaSaida")) {
            ConSai.NomeFornecedorViaF12(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()));
        } else if (Meleca.equals("ConsultaViagem")) {
            ConVia.NomeTecnicoViaF12(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()));
        } else if (Meleca.equals("RelatorioEntrada")) {
            RelEnt.NomeFornecedorViaF12(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()));
        } else if (Meleca.equals("RelatorioSaida")) {
            RelSai.NomeFornecedorViaF12(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()));
        } else if (Meleca.equals("RelatorioViagem")) {
            RelVia.NomeFornecedorViaF12(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()));
        } else if (Meleca.equals("FornecedorOrcamento")) {
            MovOrc.NomeFornecedorViaF12(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()));
        } else if (Meleca.equals("ConsultaOrcamento")) {
            ConOrc.NomeFornecedorViaF12(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()));
        }


        this.dispose();

    }//GEN-LAST:event_jTable1MouseClicked

    private void jtfPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            CarregaPessoa();
        }
    }//GEN-LAST:event_jtfPesquisaKeyPressed


    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubPesquisaPessoa().setVisible(true);
            }
        });
    }

    public void centralizar(JDesktopPane dp) {
        Dimension ds = dp.getSize();
        Dimension dw = this.getSize();
        this.setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }
    
    public void Validador(String Parametro){
        this.Meleca =  Parametro;        
    }
    
    public void SetSubFornecedor(MovimentacaoEntrada Me){
        this.MovEnt = Me;
    }
    
    public void SetSubFornecedor(MovimentacaoSaida Ms){
        this.MovSai = Ms;
    }
    
    public void SetSubViagemAbrir(MovimentacaoViagemAbrir MVA){
        this.MovViaA = MVA;
    }
    
    public void SetSubConsultaEntrada(ConsultaEntrada CE){
        this.ConEnt = CE;
    }
    
    public void SetSubConsultaSaida(ConsultaSaida CS){
        this.ConSai = CS;
    }
    
    public void SetSubConsultaViagem(ConsultaViagem CV){
        this.ConVia = CV;
    }
    
    public void SetSubRelatorioEntrada(RelatorioEntrada RE){
        this.RelEnt = RE;
    }
    
    public void SetSubRelatorioSaida(RelatorioSaida RS){
        this.RelSai = RS;
    }

    public void SetSubRelatorioViagem(RelatorioViagem RV){
        this.RelVia = RV;
    }
    
    public void SetSubFornecedorOrcamento(MovimentacaoOrcamento MO){
        this.MovOrc = MO;
    }
    
    public void SetSubConsultaOrcamento(ConsultaOrcamento CO){
        this.ConOrc = CO;
    }
    
    private void CarregaPessoa(){

        String SQL;

        SQL = "select tp.codigo, tp.nome from t_pessoa tp ";
        SQL = SQL + "where UPPER(tp.nome) like '%" + jtfPesquisa.getText().toUpperCase() + "%' ";
        SQL = SQL + "and tp.exclusao = 0 ";
        
        if (Meleca.equals("ViagemAbrir")) {
            SQL = SQL + "and chkfuncionario = 1 ";
        }
        
        SQL = SQL + "order by tp.codigo ";

        ((DefaultTableModel) jTable1.getModel()).setNumRows(0);
        jTable1.updateUI();

        Conexao = new ConexaoPostgresql();
        Conexao.Conectar() ;
        Conexao.setSQL(SQL);

        ResultSet RS = Conexao.Consultar();

        try{

            while (RS.next()){
                DefaultTableModel Tabela = (DefaultTableModel) jTable1.getModel();
                Object[] CarLinha = {RS.getString("codigo"),RS.getString("nome")};
                Tabela.addRow(CarLinha);
            }

        }catch (Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro na validação: " + Erro);
        }

        Conexao.Desconectar();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtfPesquisa;
    // End of variables declaration//GEN-END:variables

}
