/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mdiBrain.java
 *
 * Created on 29/12/2009, 10:02:51
 */

package bluecompactsystem;

import classes.ConexaoPostgresql;
import telas.CadastroAgenda;
import telas.CadastroPais;
import telas.CadastroProduto;
import telas.CadastroUnidade;
import telas.CadastroCidade;
import telas.CadastroEstado;
import telas.CadastroMaoDeObra;
import telas.ConsultaAgenda;
import telas.RelatorioAgenda;
import telas.RelatorioProduto;
import telas.ConsultaEntrada;
import telas.ConsultaOrcamento;
import telas.ConsultaProdutos;
import telas.ConsultaSaida;
import telas.ConsultaViagem;
import telas.MovimentacaoEntrada;
import telas.MovimentacaoOrcamento;
import telas.MovimentacaoSaida;
import telas.MovimentacaoViagem;
import telas.RelatorioEntrada;
import telas.RelatorioSaida;
import telas.RelatorioViagem;

/**
 *
 * @author Jeff
 */
public class mdiBlueCompactSystem extends javax.swing.JFrame {

    private ConexaoPostgresql Conexao;
    

    public void setConexao(ConexaoPostgresql Conexao) {
        this.Conexao = Conexao;
    }

    /** Creates new form mdiBrain */
    public mdiBlueCompactSystem() {
//        try {            
//            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());  // Windows
//            SwingUtilities.updateComponentTreeUI(this);

//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("com.sun.java.swing.plaf.windows.windowsLookAndFeel".equals(info.getClassName())) {   
//                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                   break;
//                 } 
//            }  
            
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("com.sun.java.swing.plaf.gtk.GTKLookAndFeel".equals(info.getClassName())) {   
//                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                   break;
//                 } 
//            }     
            
//        } catch (Exception e){            
//            e.printStackTrace();            
//        }

        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpBrain = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuArquivo = new javax.swing.JMenu();
        jmnFederações = new javax.swing.JMenu();
        jmiPais = new javax.swing.JMenuItem();
        jmiEstado = new javax.swing.JMenuItem();
        jmiCidade = new javax.swing.JMenuItem();
        jmnTipo = new javax.swing.JMenu();
        jmiUnidade = new javax.swing.JMenuItem();
        mniAgenda = new javax.swing.JMenuItem();
        jmiProduto = new javax.swing.JMenuItem();
        jmiMaoDeObra = new javax.swing.JMenuItem();
        jmnMovimentacao = new javax.swing.JMenu();
        jmnOrcamento = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmiMovimentacaoViagem = new javax.swing.JMenuItem();
        jmnConsultas = new javax.swing.JMenu();
        jmnConsArquivo = new javax.swing.JMenu();
        jmiConsAgenda = new javax.swing.JMenuItem();
        jmiConsultaProdutos = new javax.swing.JMenuItem();
        jmnConsultaMovimentacao = new javax.swing.JMenu();
        jmiConsOrcamento = new javax.swing.JMenuItem();
        jmiConsultaEntrada = new javax.swing.JMenuItem();
        jmiConsultaSaida = new javax.swing.JMenuItem();
        jmiConsultaViagem = new javax.swing.JMenuItem();
        jmnRelatorio = new javax.swing.JMenu();
        jmnRelArquivo = new javax.swing.JMenu();
        jmiRelAgenda = new javax.swing.JMenuItem();
        jmiRelProduto = new javax.swing.JMenuItem();
        jmnRelMovimentacao = new javax.swing.JMenu();
        jmiRelEntrada = new javax.swing.JMenuItem();
        jmiRelSaida = new javax.swing.JMenuItem();
        jmiRelViagem = new javax.swing.JMenuItem();
        jmnSobre = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blue Compact System 0.1 - UNSTABLE");

        jdpBrain.setBackground(new java.awt.Color(204, 204, 204));
        jdpBrain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jdpBrain.setForeground(new java.awt.Color(204, 204, 204));

        mnuArquivo.setText("Arquivo");

        jmnFederações.setText("Federações");

        jmiPais.setText("País");
        jmiPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPaisActionPerformed(evt);
            }
        });
        jmnFederações.add(jmiPais);

        jmiEstado.setText("Estado");
        jmiEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEstadoActionPerformed(evt);
            }
        });
        jmnFederações.add(jmiEstado);

        jmiCidade.setText("Cidade");
        jmiCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCidadeActionPerformed(evt);
            }
        });
        jmnFederações.add(jmiCidade);

        mnuArquivo.add(jmnFederações);

        jmnTipo.setText("Tipo");

        jmiUnidade.setText("Unidade");
        jmiUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnidadeActionPerformed(evt);
            }
        });
        jmnTipo.add(jmiUnidade);

        mnuArquivo.add(jmnTipo);

        mniAgenda.setText("Agenda");
        mniAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAgendaActionPerformed(evt);
            }
        });
        mnuArquivo.add(mniAgenda);

        jmiProduto.setText("Produto");
        jmiProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProdutoActionPerformed(evt);
            }
        });
        mnuArquivo.add(jmiProduto);

        jmiMaoDeObra.setText("Mão de Obra");
        jmiMaoDeObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMaoDeObraActionPerformed(evt);
            }
        });
        mnuArquivo.add(jmiMaoDeObra);

        menuBar.add(mnuArquivo);

        jmnMovimentacao.setText("Movimentação");

        jmnOrcamento.setText("Orçamento");
        jmnOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnOrcamentoActionPerformed(evt);
            }
        });
        jmnMovimentacao.add(jmnOrcamento);

        jMenuItem1.setText("Entrada");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmnMovimentacao.add(jMenuItem1);

        jMenuItem2.setText("Saída");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmnMovimentacao.add(jMenuItem2);

        jmiMovimentacaoViagem.setText("Viagem");
        jmiMovimentacaoViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMovimentacaoViagemActionPerformed(evt);
            }
        });
        jmnMovimentacao.add(jmiMovimentacaoViagem);

        menuBar.add(jmnMovimentacao);

        jmnConsultas.setText("Consultas");

        jmnConsArquivo.setText("Arquivo");

        jmiConsAgenda.setText("Agenda");
        jmiConsAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsAgendaActionPerformed(evt);
            }
        });
        jmnConsArquivo.add(jmiConsAgenda);

        jmiConsultaProdutos.setText("Produtos");
        jmiConsultaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultaProdutosActionPerformed(evt);
            }
        });
        jmnConsArquivo.add(jmiConsultaProdutos);

        jmnConsultas.add(jmnConsArquivo);

        jmnConsultaMovimentacao.setText("Movimentação");

        jmiConsOrcamento.setText("Orçamento");
        jmiConsOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsOrcamentoActionPerformed(evt);
            }
        });
        jmnConsultaMovimentacao.add(jmiConsOrcamento);

        jmiConsultaEntrada.setText("Entrada");
        jmiConsultaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultaEntradaActionPerformed(evt);
            }
        });
        jmnConsultaMovimentacao.add(jmiConsultaEntrada);

        jmiConsultaSaida.setText("Saída");
        jmiConsultaSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultaSaidaActionPerformed(evt);
            }
        });
        jmnConsultaMovimentacao.add(jmiConsultaSaida);

        jmiConsultaViagem.setText("Viagem");
        jmiConsultaViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultaViagemActionPerformed(evt);
            }
        });
        jmnConsultaMovimentacao.add(jmiConsultaViagem);

        jmnConsultas.add(jmnConsultaMovimentacao);

        menuBar.add(jmnConsultas);

        jmnRelatorio.setText("Relatórios");

        jmnRelArquivo.setText("Arquivo");

        jmiRelAgenda.setText("Agenda");
        jmiRelAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelAgendaActionPerformed(evt);
            }
        });
        jmnRelArquivo.add(jmiRelAgenda);

        jmiRelProduto.setText("Produto");
        jmiRelProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelProdutoActionPerformed(evt);
            }
        });
        jmnRelArquivo.add(jmiRelProduto);

        jmnRelatorio.add(jmnRelArquivo);

        jmnRelMovimentacao.setText("Movimentação");

        jmiRelEntrada.setText("Entrada");
        jmiRelEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelEntradaActionPerformed(evt);
            }
        });
        jmnRelMovimentacao.add(jmiRelEntrada);

        jmiRelSaida.setText("Saída");
        jmiRelSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelSaidaActionPerformed(evt);
            }
        });
        jmnRelMovimentacao.add(jmiRelSaida);

        jmiRelViagem.setText("Viagem");
        jmiRelViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelViagemActionPerformed(evt);
            }
        });
        jmnRelMovimentacao.add(jmiRelViagem);

        jmnRelatorio.add(jmnRelMovimentacao);

        menuBar.add(jmnRelatorio);

        jmnSobre.setText("Sobre");

        jMenuItem3.setText("Preferências");
        jmnSobre.add(jMenuItem3);

        jMenuItem4.setText("Sobre o Sistema");
        jmnSobre.add(jMenuItem4);

        menuBar.add(jmnSobre);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpBrain, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpBrain, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAgendaActionPerformed
        CadastroAgenda Agn = new CadastroAgenda();
        jdpBrain.add(Agn);
        Agn.centralizar(jdpBrain);
        Agn.setVisible(true);
    }//GEN-LAST:event_mniAgendaActionPerformed

    private void jmiCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCidadeActionPerformed
        CadastroCidade Cid = new CadastroCidade();
        jdpBrain.add(Cid);
        Cid.centralizar(jdpBrain);
        Cid.setVisible(true);
    }//GEN-LAST:event_jmiCidadeActionPerformed

    private void jmiEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEstadoActionPerformed
        CadastroEstado Est = new CadastroEstado();
        jdpBrain.add(Est);
        Est.centralizar(jdpBrain);
        Est.setVisible(true);
    }//GEN-LAST:event_jmiEstadoActionPerformed

    private void jmiPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPaisActionPerformed
        CadastroPais Pa = new CadastroPais();
        jdpBrain.add(Pa);
        Pa.centralizar(jdpBrain);
        Pa.setVisible(true);
    }//GEN-LAST:event_jmiPaisActionPerformed

    private void jmiProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProdutoActionPerformed
        CadastroProduto Cp = new CadastroProduto();
        jdpBrain.add(Cp);
        Cp.centralizar(jdpBrain);
        Cp.setVisible(true);
    }//GEN-LAST:event_jmiProdutoActionPerformed

    private void jmiRelAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelAgendaActionPerformed
        RelatorioAgenda RA = new RelatorioAgenda();
        jdpBrain.add(RA);
        RA.centralizar(jdpBrain);
        RA.setVisible(true);
    }//GEN-LAST:event_jmiRelAgendaActionPerformed

    private void jmiRelProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelProdutoActionPerformed
        RelatorioProduto RP = new RelatorioProduto();
        jdpBrain.add(RP);
        RP.centralizar(jdpBrain);
        RP.setVisible(true);
    }//GEN-LAST:event_jmiRelProdutoActionPerformed

    private void jmiUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnidadeActionPerformed
        CadastroUnidade Cu = new CadastroUnidade();
        jdpBrain.add(Cu);
        Cu.centralizar(jdpBrain);
        Cu.setVisible(true);
    }//GEN-LAST:event_jmiUnidadeActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        MovimentacaoEntrada ME = new MovimentacaoEntrada();
        jdpBrain.add(ME);
        ME.centralizar(jdpBrain);
        ME.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        MovimentacaoSaida MS = new MovimentacaoSaida();
        jdpBrain.add(MS);
        MS.centralizar(jdpBrain);
        MS.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmiMovimentacaoViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMovimentacaoViagemActionPerformed
        MovimentacaoViagem MV = new MovimentacaoViagem();
        jdpBrain.add(MV);
        MV.centralizar(jdpBrain);
        MV.setVisible(true);
    }//GEN-LAST:event_jmiMovimentacaoViagemActionPerformed

    private void jmiConsultaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultaProdutosActionPerformed
        ConsultaProdutos ConsP = new ConsultaProdutos();
        jdpBrain.add(ConsP);
        ConsP.centralizar(jdpBrain);
        ConsP.setVisible(true);
    }//GEN-LAST:event_jmiConsultaProdutosActionPerformed

    private void jmiConsultaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultaEntradaActionPerformed
        ConsultaEntrada ConsE = new ConsultaEntrada();
        jdpBrain.add(ConsE);
        ConsE.centralizar(jdpBrain);
        ConsE.setVisible(true);
    }//GEN-LAST:event_jmiConsultaEntradaActionPerformed

    private void jmiConsultaSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultaSaidaActionPerformed
        ConsultaSaida ConsS = new ConsultaSaida();
        jdpBrain.add(ConsS);
        ConsS.centralizar(jdpBrain);
        ConsS.setVisible(true);
    }//GEN-LAST:event_jmiConsultaSaidaActionPerformed

    private void jmiConsultaViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultaViagemActionPerformed
        ConsultaViagem ConsV = new ConsultaViagem();
        jdpBrain.add(ConsV);
        ConsV.centralizar(jdpBrain);
        ConsV.setVisible(true);
    }//GEN-LAST:event_jmiConsultaViagemActionPerformed

    private void jmiRelSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelSaidaActionPerformed
        RelatorioSaida RelS = new RelatorioSaida();
        jdpBrain.add(RelS);
        RelS.centralizar(jdpBrain);
        RelS.setVisible(true);
    }//GEN-LAST:event_jmiRelSaidaActionPerformed

    private void jmiRelViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelViagemActionPerformed
        RelatorioViagem RelV = new RelatorioViagem();
        jdpBrain.add(RelV);
        RelV.centralizar(jdpBrain);
        RelV.setVisible(true);
    }//GEN-LAST:event_jmiRelViagemActionPerformed

    private void jmiRelEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelEntradaActionPerformed
        RelatorioEntrada RelE = new RelatorioEntrada();
        jdpBrain.add(RelE);
        RelE.centralizar(jdpBrain);
        RelE.setVisible(true);
    }//GEN-LAST:event_jmiRelEntradaActionPerformed

    private void jmiMaoDeObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMaoDeObraActionPerformed
        CadastroMaoDeObra CadMDO = new CadastroMaoDeObra();
        jdpBrain.add(CadMDO);
        CadMDO.centralizar(jdpBrain);
        CadMDO.setVisible(true);
    }//GEN-LAST:event_jmiMaoDeObraActionPerformed

    private void jmiConsAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsAgendaActionPerformed
        ConsultaAgenda ConsAgn = new ConsultaAgenda();
        jdpBrain.add(ConsAgn);
        ConsAgn.centralizar(jdpBrain);
        ConsAgn.setVisible(true);
    }//GEN-LAST:event_jmiConsAgendaActionPerformed

    private void jmnOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnOrcamentoActionPerformed
        MovimentacaoOrcamento MovOrc = new MovimentacaoOrcamento();
        jdpBrain.add(MovOrc);
        MovOrc.centralizar(jdpBrain);
        MovOrc.setVisible(true);
    }//GEN-LAST:event_jmnOrcamentoActionPerformed

    private void jmiConsOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsOrcamentoActionPerformed
        ConsultaOrcamento ConOrc = new ConsultaOrcamento();
        jdpBrain.add(ConOrc);
        ConOrc.centralizar(jdpBrain);
        ConOrc.setVisible(true);
    }//GEN-LAST:event_jmiConsOrcamentoActionPerformed
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mdiBlueCompactSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JDesktopPane jdpBrain;
    private javax.swing.JMenuItem jmiCidade;
    private javax.swing.JMenuItem jmiConsAgenda;
    private javax.swing.JMenuItem jmiConsOrcamento;
    private javax.swing.JMenuItem jmiConsultaEntrada;
    private javax.swing.JMenuItem jmiConsultaProdutos;
    private javax.swing.JMenuItem jmiConsultaSaida;
    private javax.swing.JMenuItem jmiConsultaViagem;
    private javax.swing.JMenuItem jmiEstado;
    private javax.swing.JMenuItem jmiMaoDeObra;
    private javax.swing.JMenuItem jmiMovimentacaoViagem;
    private javax.swing.JMenuItem jmiPais;
    private javax.swing.JMenuItem jmiProduto;
    private javax.swing.JMenuItem jmiRelAgenda;
    private javax.swing.JMenuItem jmiRelEntrada;
    private javax.swing.JMenuItem jmiRelProduto;
    private javax.swing.JMenuItem jmiRelSaida;
    private javax.swing.JMenuItem jmiRelViagem;
    private javax.swing.JMenuItem jmiUnidade;
    private javax.swing.JMenu jmnConsArquivo;
    private javax.swing.JMenu jmnConsultaMovimentacao;
    private javax.swing.JMenu jmnConsultas;
    private javax.swing.JMenu jmnFederações;
    private javax.swing.JMenu jmnMovimentacao;
    private javax.swing.JMenuItem jmnOrcamento;
    private javax.swing.JMenu jmnRelArquivo;
    private javax.swing.JMenu jmnRelMovimentacao;
    private javax.swing.JMenu jmnRelatorio;
    private javax.swing.JMenu jmnSobre;
    private javax.swing.JMenu jmnTipo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mniAgenda;
    private javax.swing.JMenu mnuArquivo;
    // End of variables declaration//GEN-END:variables

}
